// @vitest-environment node
import { describe, it, expect } from "vitest";
import { canonicalMessage } from "./canonicalSign";

const OWNER = "aa".repeat(32);
const hex = (u: Uint8Array) => Buffer.from(u).toString("hex");

// Golden vectors generated by chain/agentic/testnet/signing.py::canonical_message
// (nonce=7, owner="aa"*32). Wallet-index keys stripped; transact amount = microAGNTC.
const GOLDEN: Record<string, [string, Record<string, unknown>, string]> = {
  secure:   ["secure",   { duration_blocks: 10 },
    "4167656e7469633a54783a7631007b22616374696f6e223a22736563757265222c22636861696e5f6964223a22746573746e6574222c226e6f6e6365223a372c226f776e6572223a2261616161616161616161616161616161616161616161616161616161616161616161616161616161616161616161616161616161616161616161616161616161222c22706172616d73223a7b226475726174696f6e5f626c6f636b73223a31307d7d"],
  claim:    ["claim",    { stake: 200, x: 3, y: -2 },
    "4167656e7469633a54783a7631007b22616374696f6e223a22636c61696d222c22636861696e5f6964223a22746573746e6574222c226e6f6e6365223a372c226f776e6572223a2261616161616161616161616161616161616161616161616161616161616161616161616161616161616161616161616161616161616161616161616161616161222c22706172616d73223a7b227374616b65223a3230302c2278223a332c2279223a2d327d7d"],
  transact: ["transact", { amount: 5500000, recipient_name: "alice", recipient_wallet: null },
    "4167656e7469633a54783a7631007b22616374696f6e223a227472616e73616374222c22636861696e5f6964223a22746573746e6574222c226e6f6e6365223a372c226f776e6572223a2261616161616161616161616161616161616161616161616161616161616161616161616161616161616161616161616161616161616161616161616161616161222c22706172616d73223a7b22616d6f756e74223a353530303030302c22726563697069656e745f6e616d65223a22616c696365222c22726563697069656e745f77616c6c6574223a6e756c6c7d7d"],
};

describe("canonicalMessage byte-parity with Python", () => {
  for (const [name, [action, params, expected]] of Object.entries(GOLDEN)) {
    it(`matches the Python golden vector for ${name}`, () => {
      expect(hex(canonicalMessage(action, params, OWNER, 7))).toBe(expected);
    });
  }

  it("strips wallet-index keys from params", () => {
    const withKeys = { wallet_index: 9, sender_wallet: 1, self_wallet: 2, duration_blocks: 10 };
    expect(hex(canonicalMessage("secure", withKeys, OWNER, 7))).toBe(GOLDEN.secure[2]);
  });

  it("sorts nested object keys recursively", () => {
    const a = canonicalMessage("message", { b: 1, a: { y: 2, x: 1 } }, OWNER, 0);
    const b = canonicalMessage("message", { a: { x: 1, y: 2 }, b: 1 }, OWNER, 0);
    expect(hex(a)).toBe(hex(b));
  });
});
